### ISSUE TITLE
Better OS Build version support

### ISSUE THREAD

**Issue by Slion** [Slion/VirtualDesktop#11]
Review the changes that were made in https://github.com/Slion/VirtualDesktop/commit/88cec4b2f3875c2e299f846fa0aa827886eecfd2 and consider using a `Version` object rather than a `double` to represent our OS Build.

Parsing should not assume fixed number of digits for major and minor OS Build number, namely 5 and 4 currently.

**Comment by Slion** [comment]
@mzomparelli Would be great if you could test those changes on Windows Server for instance.

**Comment by mzomparelli** [comment]
I just tested the latest repo on Win Server 2022 (my daily driver OS) and everything is still working.
