### ISSUE TITLE
Move desktop 

### ISSUE THREAD

**Issue by AkazaRenn** [Slion/VirtualDesktop#16]
Hi there, may I ask if it supports moving desktops, like in your screenshots, moving the `Dev` one to the first of the list?

In case it's not yet supported but you are interested, this PowerShell library supports that and you may take it as a reference: https://github.com/MScholtes/PSVirtualDesktop/blob/master/Module/VirtualDesktop.ps1#L357

**Comment by Slion** [comment]
Thanks for your contribution. It's been published in release v6.3.0 which should already be available on NuGet Gallery. 🥳
